### ISSUE TITLE
Pure ESM breaks CommonJS projects

### ISSUE THREAD

**Issue by ujwal-setlur** [sindresorhus/random-int#5]
I have a Typescript project that uses ``random-int`` and needs to use the ``CommonJS`` module identifier. Version 3 of ``random-int`` can't get "imported" under this scenario. Any suggestions on this? Thanks.

**Comment by sindresorhus** [comment]
Please read the release notes.

**Comment by ujwal-setlur** [comment]
Oops, missed that. Sorry
