### ISSUE TITLE
biased random integers

### ISSUE THREAD

**Issue by mfulton26** [sindresorhus/random-int#6]
I can't tell but I believe this applies. Won't `random-int` provide biased numbers?

Refs:

- [Aaron Toponce : Why The "Multiply and Floor" RNG Method Is Biased](https://pthree.org/2018/06/13/why-the-multiply-and-floor-rng-method-is-biased/)
- [ckknight/random-js: A mathematically correct random number generator library for JavaScript.](https://github.com/ckknight/random-js#readme)

**Comment by joepie91** [comment]
> For most purposes it seems like the small bias is acceptable but more sensitive cases (cryptographic, etc.) it would not be.

Biased or not, the use of `Math.random` *at all* makes this module dangerous for any kind of cryptographic use. `Math.random` is not an unpredictable random number generator, which is [one of the requirements](https://gist.github.com/joepie91/7105003c3b26e65efcea63f3db82dfba) for cryptographic use.

So yes, a warning should be added to the README stating that this module should not be used for any sort of cryptographic purpose. Probably the same applies to the 'related modules' listed in the README.
